### ISSUE TITLE
logo not up dating for me

### ISSUE THREAD

**Issue by marcus7777** [mibamur/community-polymer-elements#1]
style="filter: grayscale(0.6) opacity(0.9) hue-rotate(120deg);"

are you in chrome?

**Comment by mibamur** [comment]
today dev in firefox
is app/elements/app-logo/app-logo.html changed?

**Comment by marcus7777** [comment]
yes it's got `style="filter: grayscale(0.6) opacity(0.9) hue-rotate(120deg);"`

**Comment by mibamur** [comment]
-webkit-filter missing
repo updated

**Comment by mibamur** [comment]
done https://github.com/mibamur/community-polymer-elements/commit/3da79647b66aacfefbd613636f06036fee63b8d7
